version: '3.7'
services:
  nginx:
    container_name: spring-petclinic-nginx
    build: ./spring-petclinic-nginx
    image: adamcoakley/team-magenta-group-two:spring-petclinic-nginx
    restart: unless-stopped
    deploy:
      replicas: 1 
    networks: 
    - pc_network
    ports:
    - target: 80
      published: 80 
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  frontend:
    container_name: spring-petclinic-angular
    build: ./spring-petclinic-angular
    image: adamcoakley/team-magenta-group-two:spring-petclinic-angular
    restart: unless-stopped
    deploy:
      replicas: 1
    depends_on:
      - backend
    networks: 
      - pc_network
    ports:
    - target: 8080
      published: 8080
      protocol: tcp
  backend:
    container_name: spring-petclinic-rest
    build: ./spring-petclinic-rest
    image: adamcoakley/team-magenta-group-two:spring-petclinic-rest
    restart: unless-stopped
    deploy:
      replicas: 1
    networks: 
      - pc_network
    ports:
    - target: 9966
      published: 9966
      protocol: tcp
  db:
    build: ./spring-petclinic-db
    image: adamcoakley/team-magenta-group-two:spring-petclinic-db
    restart: always
    environment:
      MYSQL_DATABASE: 'petclinic'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'petclinic'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - petclinic-db:/var/lib/mysql
      
volumes:
  petclinic-db:

networks:
  pc_network: