---
- hosts: webservers
  become: true
  vars:
    github_repo: https://github.com/nok911/QA-petclinic-team2
    node_version: 18.13.0
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started
    - name: "Install docker dependencies"
      apt:
        pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - python3
        - python3-pip
    - name: "add gpg key"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: "add repo"
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: "Install docker engine"
      apt:
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: "Install with pip"
      pip:
        name:
          - docker
          - jsondiff
        executable: pip3


      